Initial challenge styles
netlify/compose-code-challenge pull request #2
Opened 2024-09-19 20:52 UTC by seancdavis

2024-09-20 09:23 UTC, philhawksworth commented on .gitignore
The data file is ignored from the repo because this is a build artefact. There is no action required from the participant to populate it. We don't want this to be in the repo

2024-09-20 09:25 UTC, philhawksworth commented on netlify/data.json
We can change the data structure for convenience in the code, but the bukld plugin automatically populates this so that there is no action needed by the developer. We should keep it excluded from the repo and not ask the developer to replace this.

This is how we enable the speedy route through to editing directly in github just as soon as the developer deploys the site and looks at the result.

2024-09-20 09:27 UTC, philhawksworth requested changes
Styles look great, but making the data file a manual task undoes the work to automate this for the user.

Perhaps we should add that as a comment in the readme.... but it should never actually be a mechanism they need to interact with.

2024-09-29 10:21 UTC, seancdavis commented
Closing this in favor of opening more focused PRs against current issues.

2024-09-29 10:21 UTC, closed without merging